# Generated by Django 5.1.1 on 2024-10-14 06:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='drink',
            old_name='Name',
            new_name='name',
        ),
    ]
