# Generated by Django 5.1.1 on 2024-10-14 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0002_rename_name_drink_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='uploads/')),
            ],
        ),
    ]
